---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip > /tmp/tf.zip;
            cd /tmp;
            unzip /tmp/tf.zip;
            sudo mv /tmp/terraform /usr/local/bin/terraform;
            terraform -v
      - run:
          name: Install rsync
          command: sudo apt update; sudo apt install rsync
      - run:
          name: Run tests
          command: |
            make test-all
