---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
            echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/circleci/.bash_profile;
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install build-essential && brew install terraform
      - run:
          name: Install project dependencies
          command: |
            make deps
      - run:
          name: Prepare test
          command: |
            make test-prep
      - run:
          name: Run tests
          command: |
            make test-all
