---
version: 2.1
jobs:
  build:
    environment:
      BASH_ENV: ~/.bashrc
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
            echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> $BASH_ENV
      - run:
          name: Install Terraform
          command: |
            brew install terraform node@12
            brew link --force --overwrite node@12
            echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/node@12/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install project dependencies
          command: |
            make deps
      - run:
          name: Prepare test
          command: |
            make test-prep
      - run:
          name: Run tests
          command: |
            make test-all
