---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip > /tmp/tf.zip;
            cd /tmp;
            unzip /tmp/tf.zip;
            sudo mv /tmp/terraform /usr/local/bin/terraform;
            terraform -v
      - run:
          name: Install jq and other deps
          command: sudo apt-get install rsync
      - run:
          name: Run tests
          command: |
            make test-all
